# Configuration dédiée exclusivement au développement local sur votre PC


# Docker PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# En Dev, on demande à Hibernate de créer/mettre à jour les tables automatiquement (temporaire avant Flyway)
spring.jpa.hibernate.ddl-auto=update
# On demande d'afficher les requêtes SQL dans la console pour pouvoir déboguer
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Force l'affichage des logs de configuration d'Hibernate
logging.level.org.hibernate.orm.properties=trace