name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code du dépôt GitHub, [actions] : nom de l'organisation ou du créateur du plugin ici c'est l'équipe officielle de GitHub.
      - name: Checkout source code
        uses: actions/checkout@v4 #outil qui clone le code du projet sur le serveur virtuel de GitHub pour qu'il travaille dessus, @v4 : numéro de version

      # 2. Installe Java
      - name: Set up JDK 21
        uses: actions/actions-setup-java@v4 #plugin officiel pour installer Java.
        with:
          java-version: '21'
          distribution: 'correto'
          cache: 'maven' # Cache automatique pour accélérer les futurs builds

      # 3. Donne les droits d'exécution au fichier mvnw que vous avez pushé
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      # 4. Compile le code et exécute les tests unitaires
      - name: Build and Test with Maven
        run: ./mvnw clean verify
