name: Java CI/CD Pipeline #Optionnel mais recommandé

on: #LE DÉCLENCHEUR : Quand le robot doit-il se réveiller ?
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# LES MISSIONS : Qu'est-ce que le robot doit faire ?
jobs: #Bloc qui s'exécute sur une seule machine virtuelle, Si plusieurs jobs, GitHub va démarrer plusieurs ordinateurs en parallèle dans son Cloud
  job-build-and-test:  #nom du job libre
    runs-on: ubuntu-latest #Système d'exploitation du serveur

    steps: #obligatoire, s'exécutent l'une après l'autre, dans l'ordre exact d'écriture, sur la même machine
      # 1. Récupère le code du dépôt GitHub, [actions] : nom de l'organisation ou du créateur du plugin ici c'est l'équipe officielle de GitHub.
      - name: Checkout source code
        uses: actions/checkout@v4 #outil qui clone le code du projet sur le serveur virtuel de GitHub pour qu'il travaille dessus, @v4 : numéro de version

      # 2. Installe Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4 #plugin officiel pour installer Java.
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven' # Cache automatique pour accélérer les futurs builds

      # 3. Donne les droits d'exécution au fichier mvnw que vous avez pushé
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      # 4. Compile le code et exécute les tests unitaires
        #--batch-mode : Indique à Maven qu'il tourne sur un serveur automatique. Cela nettoie les logs en évitant d'afficher des barres de téléchargement inutiles
        #--fail-at-end : C'est l'option clé pour le multi-modules. Elle ordonne à Maven de scanner tous les sous-modules déclarés, d'exécuter l'intégralité des tests de chaque enfant, et de ne donner son verdict (vert ou rouge) qu'à la toute fin.
      - name: Build and Test with Maven
        run: ./mvnw clean verify --batch-mode --fail-at-end
